'''
    GENEALOGY

    Your task is to create a class Student to represent a student
    with a name and advisor information. Student(name) should create
    a new Student object with the given name (a string), whereas
    Student(name, advisor) creates a student with an associated
    advisor (a Student object).
    The Student class should have two additional methods ancestors()
    and descendants(). The ancestors method should return a list with
    the advisor's name and recursive the advisor's ancestors names.
    The list of names should be alphabetically sorted.
    The descendants method should return a list with the names of the
    students an advisor has had, and recursively their descendants.
    The list of names should be alphabetically sorted.

    Example of usage:
    
        Ancestor tre:
    
                 Peter
                 /   \
                /     \
              Tom    Simon
               |
               |
              Dora  

        > peter = Student('Peter')
        > tom = Student('Tom', advisor=peter)
        > simon = Student('Simon', advisor=peter)
        > dora = Student('Dora', advisor=tom)
        > print(dora.ancestors())
        ['Peter', 'Tom']
        > print(peter.descendants())
        ['Dora', 'Simon', 'Tom']

    Input:  A single line with Python statements separated by semicolon.

    Output: The output generated by evaluating the input line.

    Example:

      Input:  peter = Student('Peter'); tom = Student('Tom', advisor=peter);
              simon = Student('Simon', advisor=peter); dora = Student('Dora',
              advisor=tom); print(dora.ancestors()); print(peter.descendants())

              (a single line with the above usage example)
              
      Output: ['Peter', 'Tom']
              ['Dora', 'Simon', 'Tom']
 
    Note: The below code already takes care of handling the input and output.
'''


class Student:
    # insert code
    def __init__(self, name, advisor=None): 
        self.name = name
        self.advisor = advisor
        self.students = []

        if advisor: 
            advisor.students.append(self)

    def ancestors(self): 
        if self.advisor is None: 
            return []
        return sorted([self.advisor.name] + self.advisor.ancestors())
    
    def descendants(self):
        names = []
        for student in self.students:
            names.append(student.name)
            names.extend(student.descendants())
        return sorted(names)  




exec(input())
