'''
    ELLIPSIS
    
    Python has a special value ... (three consecutive periods, that can also be
    written as Ellipsis).
    
    Your task is to write a function expand(L), that takes a list L, where all
    values are either integers or ... , and where ... always is between two
    integers in the list.  The function expand(L) should return the same list
    of integers, except that if ... is between two integers x and y, where
    x < y, then ... should be replaced by the y - x - 1 integers x + 1 to y - 1
    in increasing order.  If x > y, then ... should be replaced by the x - y - 1
    integers x - 1 to y + 1 in decreasing order. If x == y, then ... should
    be removed.

    Input:  A single Python expression using the expand function. It is
            guaranteed that the argument to expand is a list only containing
            integers and ..., and that all ... are between two integers.

    Output: The list of integers generated by executing the expression.
            It is guaranteed that the output contains at most 100 integers.

    Example:

      Input:  expand([1, 5, ..., 8, 7, ..., 4])

      Output: [1, 5, 6, 7, 8, 7, 6, 5, 4]

    Note: The below code already handles reading and executing the input.
'''


def expand(L):
    # insert code
    out = []
    for i in range(len(L)): 
        if isinstance(L[i], int): 
            out.append(L[i])
        
        elif L[i-1] < L[i+1]: 
            y = L[i-1] + 1
            while y < L[i+1]: 
                out.append(y)
                y += 1
        
        elif L[i-1] > L[i+1]: 
            y = L[i-1] - 1
            while y > L[i+1]: 
                out.append(y)
                y -= 1
    
    return out


print(eval(input()))
