'''
    REMOVE ODD

    Write a function remove_odd(L), that removes all odd integers from a list
    of integers L.

    Input:  Multiple lines of Python code using the function remove_odd.
            The last line should start with '#eof' (indicating end of file).
            The argument to remove_odd will contain at most 1000000 integers.
            The function remove_odd should modify the input list and not
            return a new list.

    Output: The output generated by executing the input code.

    Example:

      Input:  L = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
              remove_odd(L)
              print(L)
              #eof

      Output: [2, 4, 6, 8, 10]

    Note: The below code already handles reading and executing the input.
'''


def remove_odd(L):
    # insert code
    L[:] = [n for n in L if n % 2 == 0]


import sys
code = ''
for line in sys.stdin:
    code += line
    if line.startswith('#eof'):
        break
exec(code)
