'''
    PAINTING

    Your task is to write a class Painting that represents a painting. 
    The painting is a rectangular area of a given width and height,
    where the lower-left corner is (0, 0) and the upper-right corner is
    (width - 1, height - 1). The painting is initially filled with the
    symbol '.', and on the painting one can draw rectangles with any symbol.
    The below is an example of such a painting.

        ....................
        .................C..
        .....AAAAA.......C..
        ..BBBBBBBBBBB....C..
        ..BBBBBBBBBBB....C..
        .....AAAAA.......C..
        .....AAAAA.......C..
        .................C..
        ####################
        ####################
        
    The painting class should support the following:

        Painting(width, height)
            Create a painting of size width x height, where each cell 
            contains '.'. It is guaranteed that 1 <= width <= 100 and
            1 <= height <= 100.

        Painting(width, height, symbol)
            Create a painting as above, but where all cells contain symbol.

        str(painting)
            Returns a single string representation of the Painting object
            painting, where the rows in the painting are separated by '\n'.
            (Hint: Implement the __str__ method)

        painting.rectangle(x1, y1, x2, y2, symbol)
            Fills the rectangle in the Painting object painting with symbol. 
            The rectangle is defined by the lower-left corner (x1, y1)
            and the upper-right corner (x2, y2) to be filled. It is 
            guaranteed that 0 <= x1 <= x2 < width and 0 <= y1 <= y2 < height.
  
    Input:  Multiple lines of Python code using the class Painting, terminated
            with a line containing '#eof' (indicating end of file).

    Output: The output generated by executing the input code.
    
    Example:

        Input:  P = Painting(20, 10)
                P.rectangle(0, 0, 19, 1, '#')
                P.rectangle(5, 3, 9, 7, 'A')
                P.rectangle(2, 5, 12, 6, 'B')
                P.rectangle(17, 2, 17, 8, 'C')
                print(P)
                #eof

        Output: ....................
                .................C..
                .....AAAAA.......C..
                ..BBBBBBBBBBB....C..
                ..BBBBBBBBBBB....C..
                .....AAAAA.......C..
                .....AAAAA.......C..
                .................C..
                ####################
                #################### 

    Note: The below code already handles reading and executing the input.
'''


class Painting:
    # insert code
    def __init__(self, width, height, symbol='.'): 
        self.width = width
        self.height = height
        self.canvas = [[symbol for _ in range(width)] for _ in range(height)]

    def __str__(self): 
        out = []
        for row in self.canvas: 
            out.append("".join(row))
        return '\n'.join(out)
            

    def rectangle(self, x1, y1, x2, y2, symbol):
        x = x1
        while x <= x2: 
            y = y1
            while y <= y2: 
                self.canvas[self.height-1 - y][x] = symbol
                y += 1
            x += 1
            




import sys
code = ''
for line in sys.stdin:
    code += line
    if line.startswith('#eof'):
        break
exec(code)
