'''
    DIFF

    Create a generator diff(sequence) that given a sequence generates the
    difference between each consecutive pair of elements in the sequence, i.e.,
    if the sequence contains x1, x2, x3, x4, ... the generator should 
    generate the sequence x2 - x1, x3 - x2, x4 - x3, ...
    
    The sequence should be able to be any iterable.

    If the input sequence contains less than two elements, the empty sequence
    should be generated.

    Input:  Multiple lines of Python code using the generator diff, terminated 
            with a line containing '#eof' (indicating end of file).
 
    Output: The output generated by executing the input code.

    Example:

      Input:  sequence = [0, 1, 4, 9, 16, 25, 36, 49, 64]
              for d in diff(sequence):  
                  print(d)
              #eof

      Output: 1
              3
              5
              7
              9
              11
              13
              15

    Note: The below code already reads and executes the input code.
'''


# insert code
def diff(sequence): 
    for i, value in enumerate(sequence):
        if i > 0:
            yield value - last
        last = value


import sys
code = ''
for line in sys.stdin:
    code += line
    if line.startswith('#eof'):
        break
exec(code)