'''
    PERIODIC

    Assume a function f is defined on integers in an interval [start, end[.  
    Write a decorator periodic(start, end) that extends the function to be
    defined on all integers, such that for any integer x in [start, end[ and
    any integer d:
    
        f(x + d * (end - start)) = f(x)

    E.g. if we define f as
        
        @periodic(10, 15)
        def f(x):
            return 2 * x

    then f(22) = f(12 + 2 * (15 - 10)) = f(12) = 2 * 12 = 24.

    If the decorator periodic is only given one argument, periodic(end), 
    then this should be equivalent to calling periodic(0, end).

    Input:  Multiple lines of Python code using the decorator periodic.
            The last line should start with '#eof' (indicating end of file).
            It is guaranteed that if periodic is called with two arguments,
            i.e., periodic(start, end), then start and end are both integers
            and start < end. Otherwise, periodic is only called with one
            argument, i.e. periodic(end), and end is a positive integer.

    Output: The output generated by executing the input code.

    Example:

      Input:  @periodic(10, 15)
              def f(x):
                  return 2 * x

              print(f(10), f(14), f(15), f(6), f(22), f(-4))

              #eof

      Output: 20 28 20 22 24 22
    
    Note: The below code already handles reading and executing the input.
'''


# insert code
def periodic(start, end=None):
    if end == None:
        start, end = 0, start
    
    def decorator(f): 
        def wrapper(x):
            interval = end - start
            return f((x-start) % interval + start)
        return wrapper
    return decorator
            


import sys
code = ''
for line in sys.stdin:
    code += line
    if line.startswith('#eof'):
        break
exec(code)